class CommonText(object):
    def __init__(self):
        self.appliedCharacterStyle = None
        self.appliedConditions = None
        self.appliedLanguage = None
        self.appliedParagraphStyle = None
        self.autoLeading = None
        self.autoTcy = None
        self.autoTcyIncludeRoman = None
        self.baselineShift = None
        self.bulletsAlignment = None
        self.bulletsAndNumberingListType = None
        self.bulletsTextAfter = None
        self.capitalization = None
        self.characterAlignment = None
        self.characterDirection = None
        self.characterRotation = None
        self.composer = None
        self.desiredGlyphScaling = None
        self.desiredLetterSpacing = None
        self.desiredWordSpacing = None
        self.diacriticPosition = None
        self.digitsType = None
        self.dropCapCharacters = None
        self.dropCapLines = None
        self.dropCapDetail = None
        self.endJoin = None
        self.fillColor = None
        self.fillTint = None
        self.firstLineIndent = None
        self.fontStyle = None
        self.glyphForm = None
        self.gotoNextX = None
        self.gradientFillAngle = None
        self.gradientFillLength = None
        self.gradientFillStart = None
        self.gradientStrokeAngle = None
        self.gradientStrokeLength = None
        self.gradientStrokeStart = None
        self.gridAlignFirstLineOnly = None
        self.gridAlignment = None
        self.horizontalScale = None
        self.hyphenWeight = None
        self.hyphenateAcrossColumns = None
        self.hyphenateAfterFirst = None
        self.hyphenateBeforeLast = None
        self.hyphenateCapitalizedWords = None
        self.hyphenateLadderLimit = None
        self.hyphenateLastWord = None
        self.hyphenateWordsLongerThan = None
        self.hyphenation = None
        self.hyphenationZone = None
        self.ignoreEdgeAlignment = None
        self.justification = None
        self.keepAllLinesTogether = None
        self.keepFirstLines = None
        self.keepLastLines = None
        self.keepLinesTogether = None
        self.keepRuleAboveInFrame = None
        self.keepWithNext = None
        self.keepWithPrevious = None
        self.kerningMethod = None
        self.kerningValue = None
        self.keyboardDirection = None
        self.lastLineIndent = None
        self.leadingModel = None
        self.leftIndent = None
        self.ligatures = None
        self.maximumGlyphScaling = None
        self.maximumLetterSpacing = None
        self.maximumWordSpacing = None
        self.minimumGlyphScaling = None
        self.minimumLetterSpacing = None
        self.minimumWordSpacing = None
        self.miterLimit = None
        self.noBreak = None
        self.numberingAlignment = None
        self.numberingRestartPolicy = None
        self.numberingContinue = None
        self.numberingExpression = None
        self.numberingLevel = None
        self.numberingStartAt = None
        self.otfContextualAlternative = None
        self.otfDiscretionaryLigature = None
        self.otfFigureStyle = None
        self.otfFraction = None
        self.otfHVKana = None
        self.otfHistorical = None
        self.otfJustificationAlternate = None
        self.otfLocale = None
        self.otfMark = None
        self.otfOrdinal = None
        self.otfOverlapSwash = None
        self.otfProportionalMetrics = None
        self.otfRomanItalics = None
        self.otfSlashedZero = None
        self.otfStretchedAlternate = None
        self.otfStylisticAlternate = None
        self.otfStylisticSets = None
        self.otfSwash = None
        self.otfTitling = None
        self.overprintFill = None
        self.overprintStroke = None
        self.pageNumberType = None
        self.paragraphDirection = None
        self.paragraphJustification = None
        self.pointSize = None
        self.position = None
        self.positionalForm = None
        self.rensuuji = None
        self.rightIndent = None
        self.rotateSingleByteCharacters = None
        self.ruleAbove = None
        self.ruleAboveGapOverprint = None
        self.ruleAboveGapTint = None
        self.ruleAboveLeftIndent = None
        self.ruleAboveLineWeight = None
        self.ruleAboveOffset = None
        self.ruleAboveOverprint = None
        self.ruleAboveRightIndent = None
        self.ruleAboveTint = None
        self.ruleAboveWidth = None
        self.ruleBelow = None
        self.ruleBelowGapOverprint = None
        self.ruleBelowGapTint = None
        self.ruleBelowLeftIndent = None
        self.ruleBelowLineWeight = None
        self.ruleBelowOffset = None
        self.ruleBelowOverprint = None
        self.ruleBelowRightIndent = None
        self.ruleBelowTint = None
        self.ruleBelowWidth = None
        self.scaleAffectsLineHeight = None
        self.singleWordJustification = None
        self.skew = None
        self.spaceAfter = None
        self.spaceBefore = None
        self.spanColumnInsideGutter = None
        self.spanColumnOutsideGutter = None
        self.spanColumnType = None
        self.spanSplitColumnCount = None
        self.startParagraph = None
        self.strikeThroughGapOverprint = None
        self.strikeThroughGapTint = None
        self.strikeThroughOffset = None
        self.strikeThroughOverprint = None
        self.strikeThroughTint = None
        self.strikeThroughWeight = None
        self.strikeThru = None
        self.strokeAlignment = None
        self.strokeColor = None
        self.strokeTint = None
        self.strokeWeight = None
        self.tracking = None
        self.treatIdeographicSpaceAsSpace = None
        self.tsume = None
        self.underline = None
        self.underlineGapOverprint = None
        self.underlineGapTint = None
        self.underlineOffset = None
        self.underlineOverprint = None
        self.underlineTint = None
        self.underlineWeight = None
        self.verticalScale = None
        self.xOffsetDiacritic = None
        self.yOffSetDiacritic = None

        self.allGrepStyles = None
        self.allLineStyles = None
        self.allNestedStyles = None
        self.appliedFont = None
        self.appliedNumberingList = None
        self.balanceRaggedLines = None
        self.bulletChar = None
        self.bulletsCharacterStyle = None
        self.bulletsFont = None
        self.bulletsFontStyle = None
        self.customGlyph = None
        self.leading = None
        self.numberingCharacterStyle = None
        self.numberingFormat = None
        self.numberingRestartPolicies = None
        self.openTypeFeatures = None
        self.ruleAboveColor = None
        self.ruleAboveGapColor = None
        self.ruleAboveType = None
        self.ruleBelowColor = None
        self.ruleBelowGapColor = None
        self.ruleBelowType = None
        self.strikeThroughColor = None
        self.strikeThroughGapColor = None
        self.strikeThroughType = None
        self.tabList = None
        self.underlineColor = None
        self.underlineGapColor = None
        self.underlineType = None

    def set_word_spacing(self, *, minimum=None, desired=None, maximum=None):
        if minimum is not None:
            self.minimumWordSpacing = minimum
        if desired is not None:
            self.desiredWordSpacing = desired
        if maximum is not None:
            self.maximumWordSpacing = maximum

    def set_glyph_scaling(self, *, minimum=None, desired=None, maximum=None):
        if minimum is not None:
            self.minimumGlyphScaling = minimum
        if desired is not None:
            self.desiredGlyphScaling = desired
        if maximum is not None:
            self.maximumGlyphScaling = maximum

    def set_letter_spacing(self, *, minimum=None, desired=None, maximum=None):
        if minimum is not None:
            self.minimumLetterSpacing = minimum
        if desired is not None:
            self.desiredLetterSpacing = desired
        if maximum is not None:
            self.maximumLetterSpacing = maximum

    def set_justification(self, *, word=None, glyph=None, letter=None):
        """Accepts up to 3 sets of tuples containing 3 values to set justification settings"""
        if isinstance(word, tuple):
            self.set_word_spacing(word[0], word[1], word[2])
        if isinstance(glyph, tuple):
            self.set_glyph_scaling(glyph[0], glyph[1], glyph[2])
        if isinstance(letter, tuple):
            self.set_letter_spacing(letter[0], letter[1], letter[2])
